apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: {{APP_NAME}}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{APP_NAME}}-db
  template:
    metadata:
      labels:
        app: {{APP_NAME}}-db
    spec:
      containers:
      - image: 10.0.0.11/demo/postgres:9.4
        name: db
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
        resources:
          limits:
            cpu: 200m
            memory: "200Mi"
          requests:
            cpu: 200m
            memory: "200Mi"
      volumes:
      - name: db-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  ports:
  - name: db
    port: 5432
    targetPort: 5432
  selector:
    app: {{APP_NAME}}-db
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{APP_NAME}}-redis
    spec:
      containers:
      - image: 10.0.0.11/demo/redis:alpine
        name: redis
        volumeMounts:
        - mountPath: /data
          name: redis-data
        resources:
          limits:
            cpu: 200m
            memory: "200Mi"
          requests:
            cpu: 200m
            memory: "200Mi"
      volumes:
      - name: redis-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app: {{APP_NAME}}-redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: result
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{APP_NAME}}-result
    spec:
      containers:
      - image: 10.0.0.11/demo/example-voting-app_result:latest
        name: result
        resources:
          requests:
            cpu: "200m"
            memory: "200Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: result
spec:
  type: NodePort
  ports:
  - name: "result-service"
    port: 5001
    targetPort: 80
    nodePort: 31001
  selector:
    app: {{APP_NAME}}-result
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vote
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{APP_NAME}}-vote
    spec:
      containers:
      - image: 10.0.0.11/demo/example-voting-app_vote:latest
        name: vote
        resources:
          requests:
            cpu: "200m"
            memory: "200Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: vote
spec:
  type: NodePort
  ports:
  - name: "vote-service"
    port: 5000
    targetPort: 80
    nodePort: 31000
  selector:
    app: {{APP_NAME}}-vote
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{APP_NAME}}-worker
    spec:
      containers:
      - image: 10.0.0.11/demo/example-voting-app_worker:latest
        name: worker
        resources:
          requests:
            cpu: "200m"
            memory: "200Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"